### ISSUE TITLE
Discord to youtube

### ISSUE THREAD

**Issue by popcorn9499** [popcorn9499/Youtube-Discord-Relay-Bot#1]
Unsure how to but i need to make it able to send to discord. I tried previously always got a authentication error

**Comment by redshojin** [comment]
Oh! sorry, the wording made me confused was all. Well, let me know if you ever figure out how to get it to work. It works great otherwise!

**Comment by popcorn9499** [comment]
I will gladly post a updated version with the working code as soon as i reread the code and youtube api and figure out the issue. It's been a little now to get myself back up to speed on the youtube api for live streaming. right?

**Comment by popcorn9499** [comment]
I officially added basic support. I will work on this in the next few days to get that finish and working perfectly but i did create some basic support. so @redshojin if you wanna check it out i just posted it.

**Comment by popcorn9499** [comment]
I currently only need to add support for different formatting methods the " : " portion in discord to youtube currently is mandatory till i implement the next update for this.

**Comment by popcorn9499** [comment]
Fixed
